### ISSUE TITLE
Error to run the code

### ISSUE THREAD

**Issue by volpatoo** [diegojgris/draw-plots-qgis#1]
Hi Diego,

First, thanks for sharing with us this amazing tool to deal with phenotyping tasks. I really appreciate that, and finally, I found something very handy to handle. However, I got this error, I do not why, but I followed all your instructions in the manual guide. Also, when I run your code using my R, everything works well, however, the issue is when I try to use it with QGIS. 

Many thanks,

Leonardo

![error](https://user-images.githubusercontent.com/44096217/121781233-d1691580-cb71-11eb-8b7c-640131c6121d.PNG)

**Comment by volpatoo** [comment]
> Hi Diego,
> 
> First, thanks for sharing with us this amazing tool to deal with phenotyping tasks. I really appreciate that, and finally, I found something very handy to handle. However, I got this error, I do not why, but I followed all your instructions in the manual guide. Also, when I run your code using my R, everything works well, however, the issue is when I try to use it with QGIS.
> 
> Many thanks,
> 
> Leonardo
> 
> ![error](https://user-images.githubusercontent.com/44096217/121781233-d1691580-cb71-11eb-8b7c-640131c6121d.PNG)

I realized that my "User library folder" was not changed according to the path from my R packages. I am using "C:/Users/leoag/Documents/R/win-library/4.1" however, the code into QGIS shows "C:/Program Files/R/R-4.1.0/library".

I am not sure how to figure out it.

**Comment by diegojgris** [comment]
Hi Leonardo,

Thank you for finding good use for my tool! I kind of expected people would have issues with R package installations, especially because I assumed users wouldn't have R previously installed. But as it seems you are a R user already, you can simply change the settings to point QGIS to your existing R library folder:
![image](https://user-images.githubusercontent.com/22935125/121782770-d11c4a80-cb70-11eb-8017-d22f1074a47d.png)
This should solve your problem. Let me know if it works!

Best,
Diego

**Comment by volpatoo** [comment]
Hello Diego,

Thanks for your support! 

I realized that my "User library folder" was not changed according to the path from my R packages. I am using "C:/Users/leoag/Documents/R/win-library/4.1" however, the code into QGIS shows "C:/Program Files/R/R-4.1.0/library".

Is there another way to change this path? 

Again, well done! This tool is amazing!

**Comment by diegojgris** [comment]
Sorry, did you also checked the box "Use user library folder instead of system libraries"? I forgot to mention that. If you check this box and you put the path to your existing library ("C:/Users/leoag/Documents/R/win-library/4.1") in "User library folder", it should work.

Thanks,
Diego

**Comment by volpatoo** [comment]
Hi Diego,
Now, this tool is working well. Actually, I did not read with attention this box, it was my mistake, sorry! 
Many thanks!

**Comment by diegojgris** [comment]
You are welcome! I am already updating the tutorial so that people do not get this error anymore. Thanks for pointing it out and let me know if you have any other errors or suggestions.

Regards,
Diego
