### ISSUE TITLE
Draw plots from clicks not showing up

### ISSUE THREAD

**Issue by NMihelich** [diegojgris/draw-plots-qgis#2]
Hello, I am interested in using the "Draw points from clicks" tool as in the readme. However, after setting up the plugin, I have the other 3 Draw tools (Excel, points, and polygons), but the clicks tool is not present. I thought it might be a mac issue, so I installed everything on my PC and had the same issue. Please advise. Thanks!
![Screen Shot 2022-04-19 at 10 30 39 PM](https://user-images.githubusercontent.com/62397224/164144862-e77c87ae-be3b-4c08-bee5-e228a3030c77.png)

**Comment by filipematias23** [comment]
Hi @NMihelich, did you figure out this issue? I am at the same page now..!

Thanks

**Comment by diegojgris** [comment]
@NMihelich, @filipematias23. It should be fixed now, there was a problem with the tool help file. Please, download the codebase again and try it. Let me know if it does not work.
