### ISSUE TITLE
Issue in the Draw plots from clicks function

### ISSUE THREAD

**Issue by Souzaph** [diegojgris/draw-plots-qgis#3]
Hello. I have heard that rgdal, rgeos and maptools are retired. Since the plugin draw-plots-qgis use them, I am having an error when I try to run the Draw plots from clicks function, and I get this error: "This script has a syntax error. Exception This command is no longer supported, `rgdal` package was removed from CRAN. with line: ##load_vector_using_rgdal".
How can we solve this problem?
Thanks in adnvance

**Comment by diegojgris** [comment]
Hi @Souzaph, I just updated the tool and it should be working now. Please try it and let me know if you have any issues.
Best,
Diego Gris
